force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <label>Appointment</label>
    <nameField>
        <displayFormat>APN-{0000}</displayFormat>
        <label>Appointment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointment__c/fields/Doctor__c.field-meta.xml
<CustomField>
    <fullName>Doctor__c</fullName>
    <label>Doctor</label>
    <referenceTo>Doctor__c</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <label>Patient</label>
    <referenceTo>Patient__c</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Slot__c.field-meta.xml
<CustomField>
    <fullName>Slot__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Slot</label>
    <referenceTo>Slot__c</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Doctor__c/Doctor__c.object-meta.xml
<CustomObject>
    <label>Doctor</label>
    <nameField>
        <label>Doctor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Doctors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Patient__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Patients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Slot__c/Slot__c.object-meta.xml
<CustomObject>
    <label>Slot</label>
    <nameField>
        <displayFormat>APS-{0000}</displayFormat>
        <label>Slots Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Slots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Slot__c/fields/Doctor__c.field-meta.xml
<CustomField>
    <fullName>Doctor__c</fullName>
    <label>Doctor</label>
    <referenceTo>Doctor__c</referenceTo>
    <relationshipLabel>Slots</relationshipLabel>
    <relationshipName>Slots</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Slot__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Session Expired</fullName>
            </value>
            <value>
                <fullName>Not Available</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CreateAppointmentController.cls
public class CreateAppointmentController {
	@AuraEnabled(cacheable=false)
    public static boolean createBooking(Id slotId, Id doctorId){
        
        String userId = UserInfo.getUserId();
        String patientId = '';
        
        Appointment__c appointment = new Appointment__c();
        appointment.Doctor__c = doctorId;
        appointment.Slot__c = slotId;
        if([SELECT Id, Name FROM Patient__c WHERE User__c =: userId].size() > 0){
            patientId = [SELECT Id FROM Patient__c WHERE User__c =: userId].Id;
            appointment.Patient__c = patientId;
        }else{
            Patient__c patient = new Patient__c();
            patient.Name = [SELECT Name FROM User WHERE Id =: userId].Name;
            patient.User__c = userId;
            patient.Email__c = [SELECT Email FROM User WHERE Id =: userId].Email;
            insert patient;
            appointment.Patient__c = [SELECT Id FROM Patient__c WHERE User__c =: userId].Id;
        }
        try {
            Database.SaveResult result = Database.insert(appointment);
            if (result.isSuccess()) {
                Slot__c slot = [SELECT Id, Status__c FROM Slot__c WHERE Id =: slotId];
                slot.Status__c = 'Booked';
                update slot;
                return true;
            } else {
                for (Database.Error error : result.getErrors()) {
                    System.debug('Error message: ' + error.getMessage());
                }
                return false;
            }
        } catch (Exception e) {
            System.debug('An error occurred: ' + e.getMessage());
            return false;
        }
    }
}